parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-explicit-any": off
